# Generated by Django 5.1 on 2024-09-13 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chatroom_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroommessage',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
