# Generated by Django 5.1 on 2024-09-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatroommessage_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='description',
            field=models.CharField(default='idk', max_length=350),
            preserve_default=False,
        ),
    ]
