# Generated by Django 5.1 on 2024-09-13 15:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chatroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
